- name: install common packages
  package: name={{ item }} state=present
  with_items:
    - emacs
    - git
    - htop
    - '{{ packages.openssh }}'
    - tmux
    - '{{ packages.vim }}'
    - zsh

- name: create build user
  user:
    name: ansible-build
    system: yes
    home: /opt/ansible-build

- name: update sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^ansible-build\s+ALL='
      line: 'ansible-build ALL=(ALL) NOPASSWD: ALL'
    - regexp: '^%{{ sudo_group }}\s+ALL='
      line: '%{{ sudo_group }} ALL=(ALL:ALL) ALL'

- include: arch.yml
  when: ansible_distribution=="Archlinux"

- include: ubuntu.yml
  when: ansible_distribution=="Ubuntu"

