- name: install dev packages
  package: name={{ item }} state=present
  with_items: '{{ dev_packages }}'

- name: install docker
  package: name=docker state=present

- name: enable and start docker
  service: name=docker state=started enabled=yes

- name: add user to docker group
  user: name=belak append=yes groups=docker

- name: install python packages
  package: name={{ item }} state=present
  with_items: '{{ python_packages }}'

# TODO: Need to install racer on Ubuntu
- name: install rust
  package: name={{ item }} state=present
  with_items: '{{ rust_packages }}'

- name: install python
  package: name={{ item }} state=present
  with_items: '{{ python_packages }}'

- name: install arm tools
  package: name={{ item }} state=present
  with_items: '{{ arm_packages }}'

- include: arch.yml
  when: ansible_distribution=="Archlinux"

- include: ubuntu.yml
  when: ansible_distribution=="Ubuntu"
